{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17459,
          "sha512": "ea78bdaf1c4dcf89a7e8bafebcc087a7ab7b36603ddb46701da0f5e7120f41915b98670a976c433e6c504e94cf2ca7932e77b73837f6c3bc4fba9d1ab1e55941",
          "sha256": "b5174f5e2d880dc559e17b27f4db34cfd1114ee4e252d27dae7dfb4d39d92347",
          "sha1": "3807cee8896a8fe28292f26cae28fb14dfc88f4e",
          "md5": "eeef5766267096bfae7e34cbae4a5949"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17459,
          "sha512": "ea78bdaf1c4dcf89a7e8bafebcc087a7ab7b36603ddb46701da0f5e7120f41915b98670a976c433e6c504e94cf2ca7932e77b73837f6c3bc4fba9d1ab1e55941",
          "sha256": "b5174f5e2d880dc559e17b27f4db34cfd1114ee4e252d27dae7dfb4d39d92347",
          "sha1": "3807cee8896a8fe28292f26cae28fb14dfc88f4e",
          "md5": "eeef5766267096bfae7e34cbae4a5949"
        }
      ]
    }
  ]
}
