{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17459,
          "sha512": "5ef1dc6ddd591110049e9299089cb4b08af6b24884dd061c801e3fb40bc27fa681532d93ac0296c6a5c81a3d91517d946d471c43db1b9b594179976da7234cae",
          "sha256": "112740ab63ae9f8f582ecc991d95333f642e891e7b66df64e82f39c512b45bc5",
          "sha1": "3b245aa637449b4fe1e47d114419f3525c24cf88",
          "md5": "b53099f887a5ffb630da8576a8dd740e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17459,
          "sha512": "5ef1dc6ddd591110049e9299089cb4b08af6b24884dd061c801e3fb40bc27fa681532d93ac0296c6a5c81a3d91517d946d471c43db1b9b594179976da7234cae",
          "sha256": "112740ab63ae9f8f582ecc991d95333f642e891e7b66df64e82f39c512b45bc5",
          "sha1": "3b245aa637449b4fe1e47d114419f3525c24cf88",
          "md5": "b53099f887a5ffb630da8576a8dd740e"
        }
      ]
    }
  ]
}
