{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17458,
          "sha512": "b024d4eac5ba64ebcf9b171fe52ae1421b5e85b0907b3e358920b3970ce84def157b2f314c4ada62a378f0ddcfdc287c97b5df71b512b4cea9e822e6dda32bdf",
          "sha256": "f1b06925060f9ee1e537c684b5f1762c778ef87f0ea25768f0dec3d8cf3ebaa6",
          "sha1": "29c751f3b19bca4aabfad77b8f7066d0fc5ba1e0",
          "md5": "31a963ad290191462299e901e7b9f590"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17458,
          "sha512": "b024d4eac5ba64ebcf9b171fe52ae1421b5e85b0907b3e358920b3970ce84def157b2f314c4ada62a378f0ddcfdc287c97b5df71b512b4cea9e822e6dda32bdf",
          "sha256": "f1b06925060f9ee1e537c684b5f1762c778ef87f0ea25768f0dec3d8cf3ebaa6",
          "sha1": "29c751f3b19bca4aabfad77b8f7066d0fc5ba1e0",
          "md5": "31a963ad290191462299e901e7b9f590"
        }
      ]
    }
  ]
}
