{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.13.jar",
          "url": "nativeBridge-script-1.0.13.jar",
          "size": 17460,
          "sha512": "7756c4e20765e7df9cea493f7d44796fe14556fabace42dfefcbc8c6bc5ae3e6ce7b54961dafb456defb384b754f0f6a43ad68c394067e3a4cc1111546efdd44",
          "sha256": "b08d53e2fc4d4760c7eca806febf472c62f32d2f656636c61396dac3b0d16003",
          "sha1": "265462975c6f2a086da7c259d20d55112b81ec67",
          "md5": "2ee67587fb568625e90fddd7591e8322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.13.jar",
          "url": "nativeBridge-script-1.0.13.jar",
          "size": 17460,
          "sha512": "7756c4e20765e7df9cea493f7d44796fe14556fabace42dfefcbc8c6bc5ae3e6ce7b54961dafb456defb384b754f0f6a43ad68c394067e3a4cc1111546efdd44",
          "sha256": "b08d53e2fc4d4760c7eca806febf472c62f32d2f656636c61396dac3b0d16003",
          "sha1": "265462975c6f2a086da7c259d20d55112b81ec67",
          "md5": "2ee67587fb568625e90fddd7591e8322"
        }
      ]
    }
  ]
}
