{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.13.jar",
          "url": "nativeBridge-script-1.0.13.jar",
          "size": 18859,
          "sha512": "41355a622496e19e8e9187d0d61e6f8fb6fb0ca9dfbe43da242a8e79f924a451670d61e3f9aea3d1091f4e7337bec0ec116e71191a133abbeb5c36e20f1b1f15",
          "sha256": "a21a70fcd52072503c0ec35824483e27978c80476f4f7f44f0eff918b2a25fe0",
          "sha1": "37cae34ea45a845f66aca62ea65fe8154411d58f",
          "md5": "96c6de19ef2b6ad03d271beb0f0baa2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.13.jar",
          "url": "nativeBridge-script-1.0.13.jar",
          "size": 18859,
          "sha512": "41355a622496e19e8e9187d0d61e6f8fb6fb0ca9dfbe43da242a8e79f924a451670d61e3f9aea3d1091f4e7337bec0ec116e71191a133abbeb5c36e20f1b1f15",
          "sha256": "a21a70fcd52072503c0ec35824483e27978c80476f4f7f44f0eff918b2a25fe0",
          "sha1": "37cae34ea45a845f66aca62ea65fe8154411d58f",
          "md5": "96c6de19ef2b6ad03d271beb0f0baa2b"
        }
      ]
    }
  ]
}
