{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.13.jar",
          "url": "nativeBridge-script-1.0.13.jar",
          "size": 18429,
          "sha512": "7a813fb6ae8bd9f58cfa8bf6d436575aa5cf7adae97e30f4e095cadb8bd077bb30279780767722ec2dd5f072c97abe2215d808c452cbb66624f1d0f3720f0f6a",
          "sha256": "0bee5e4c2c32ea37c53a0a124f8cfb691049688ee8d529023d307c51dd8a1c98",
          "sha1": "d074e6f43a86ba662a2d260641681214d0edec2d",
          "md5": "e0a593ca19437d1e6d0b0efb2e25e241"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.13.jar",
          "url": "nativeBridge-script-1.0.13.jar",
          "size": 18429,
          "sha512": "7a813fb6ae8bd9f58cfa8bf6d436575aa5cf7adae97e30f4e095cadb8bd077bb30279780767722ec2dd5f072c97abe2215d808c452cbb66624f1d0f3720f0f6a",
          "sha256": "0bee5e4c2c32ea37c53a0a124f8cfb691049688ee8d529023d307c51dd8a1c98",
          "sha1": "d074e6f43a86ba662a2d260641681214d0edec2d",
          "md5": "e0a593ca19437d1e6d0b0efb2e25e241"
        }
      ]
    }
  ]
}
