{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlex",
    "module": "gradlex",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 9176,
          "sha512": "0a6b5fc38848603a30aa6144ffdfebcb5587901c5f10ff157b8be7d50a3f4c24c235d51b2ca5b9f95519ee669c78ca83f74c0e812c10943e259be9fa981b6544",
          "sha256": "1f0a9c7e5c0efa001b5515267b544392002da04376a44bdcebe1192d1c94d14b",
          "sha1": "b6f113cef7cd3231292f37f8c8c49f13a9c6af19",
          "md5": "033f4fe86a8265fefd9dd1606cb0670b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 9176,
          "sha512": "0a6b5fc38848603a30aa6144ffdfebcb5587901c5f10ff157b8be7d50a3f4c24c235d51b2ca5b9f95519ee669c78ca83f74c0e812c10943e259be9fa981b6544",
          "sha256": "1f0a9c7e5c0efa001b5515267b544392002da04376a44bdcebe1192d1c94d14b",
          "sha1": "b6f113cef7cd3231292f37f8c8c49f13a9c6af19",
          "md5": "033f4fe86a8265fefd9dd1606cb0670b"
        }
      ]
    }
  ]
}
