{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.4/nativeBridge-annotation-1.0.4.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation.klib",
          "url": "nativeBridge-annotation-iosarm64-1.0.4.klib",
          "size": 23723,
          "sha512": "06e2747b0b9509b9d49e41fd22edcc7ed953a7d12781fcaec61105dd4479a884bea0f50fbf9df798f144eb49fd5a1233526f2a4f6e78791b4ebdf78bdf9297a2",
          "sha256": "60c46c45f1c769a40b215989ff76c95f52993ca4e364d01797384a46d42b7a28",
          "sha1": "5dac3a4fc2ba705a026e71182ef36ecb75491745",
          "md5": "7f992812ac970accc20e7aa28ff6ba86"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-iosarm64-1.0.4-sources.jar",
          "url": "nativeBridge-annotation-iosarm64-1.0.4-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-iosarm64-1.0.4-metadata.jar",
          "url": "nativeBridge-annotation-iosarm64-1.0.4-metadata.jar",
          "size": 261,
          "sha512": "8f2eb75f028e0c7e39a639e626f200bef285ff68f8a3b34f41b5ab6decd400298b4ae9a3ffe59637c9032619bc13e12d1f213c75b32ea655b41a6387d136be77",
          "sha256": "a4d5145eb7a41636d38c3fee432716d4608fb3e2dd94930b1f151bb5d3edbf0f",
          "sha1": "94886cede2e58bbe1f25e45fb8fa8a09a6946ff2",
          "md5": "48c3f057e8aa00a139e1321043b0db3b"
        }
      ]
    }
  ]
}
