{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-gradle",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-gradle-1.0.2.jar",
          "url": "nativeBridge-gradle-1.0.2.jar",
          "size": 17457,
          "sha512": "e754a74ba24517a9a3c44d3e0d9a0c317bef07429dbce99f00deb794e8ba58a67e3def5514d3a1488bd489a51d9b6f42d9376d40037e96a5ef860c25c3ededab",
          "sha256": "160c606b32a720a9b99c3c5c479ecf78363d740f9bf13c13a9eb963084e67bfe",
          "sha1": "9c4008aa21a3a5922dbb18e540d1757f693edde9",
          "md5": "c55c9180dd4db791871e5450df554db9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-gradle-1.0.2.jar",
          "url": "nativeBridge-gradle-1.0.2.jar",
          "size": 17457,
          "sha512": "e754a74ba24517a9a3c44d3e0d9a0c317bef07429dbce99f00deb794e8ba58a67e3def5514d3a1488bd489a51d9b6f42d9376d40037e96a5ef860c25c3ededab",
          "sha256": "160c606b32a720a9b99c3c5c479ecf78363d740f9bf13c13a9eb963084e67bfe",
          "sha1": "9c4008aa21a3a5922dbb18e540d1757f693edde9",
          "md5": "c55c9180dd4db791871e5450df554db9"
        }
      ]
    }
  ]
}
