{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.6.jar",
          "url": "nativeBridge-script-1.0.6.jar",
          "size": 17458,
          "sha512": "843a1a729a0d0b97097091cb78d353de4e89dfea08e1e7f0e32ffa05ebfb37fb89d10a54c48154e48e3e6f3aec988136796ad818453539281b7da569e2eae34b",
          "sha256": "37d7e69a175127cc614f7fbb6b7872998f055bd6b5f96b2df14b71a685051422",
          "sha1": "88c9e22dbc4d6155ef982d6846896406dd2ac22a",
          "md5": "f94557250e800fe1b9e06287185db1fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.6.jar",
          "url": "nativeBridge-script-1.0.6.jar",
          "size": 17458,
          "sha512": "843a1a729a0d0b97097091cb78d353de4e89dfea08e1e7f0e32ffa05ebfb37fb89d10a54c48154e48e3e6f3aec988136796ad818453539281b7da569e2eae34b",
          "sha256": "37d7e69a175127cc614f7fbb6b7872998f055bd6b5f96b2df14b71a685051422",
          "sha1": "88c9e22dbc4d6155ef982d6846896406dd2ac22a",
          "md5": "f94557250e800fe1b9e06287185db1fc"
        }
      ]
    }
  ]
}
