{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "gradlex",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 17423,
          "sha512": "01a70cb3ed6a7fe66723690e7e96f1028f5bedba8c2c497c2e8cf2a171267a26c477cfdca8c0d6421582aa67d1debba668b94243a5ff89234fdd83194b322ab2",
          "sha256": "f21562c319abae6fb7d10dcfa76a4ee115c2aa67e98c19d9e776dbc421f728a1",
          "sha1": "d4e43f35bda3838d9b49769e2a2721ca5863ca5a",
          "md5": "6f302af8733ee9e9280f55784741a142"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 17423,
          "sha512": "01a70cb3ed6a7fe66723690e7e96f1028f5bedba8c2c497c2e8cf2a171267a26c477cfdca8c0d6421582aa67d1debba668b94243a5ff89234fdd83194b322ab2",
          "sha256": "f21562c319abae6fb7d10dcfa76a4ee115c2aa67e98c19d9e776dbc421f728a1",
          "sha1": "d4e43f35bda3838d9b49769e2a2721ca5863ca5a",
          "md5": "6f302af8733ee9e9280f55784741a142"
        }
      ]
    }
  ]
}
