{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "gradlex",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 14978,
          "sha512": "d70f3526e75a95053e94bed988ad2c58efe4c1dfa563d62fcb2cf121904fac39224cf4dfeeb332e5461b9e5e3e6304391e729598d9fa0e5f082456b757b31ba9",
          "sha256": "964398ba85a0653d92ca29d6b1079c8fa87370bc579de4d822c0c85f32622aa5",
          "sha1": "8d96bc3164cb752d7c9c051b0bfd132d3ed3e524",
          "md5": "ff6602e39cdb47781707661eaba6c432"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 14978,
          "sha512": "d70f3526e75a95053e94bed988ad2c58efe4c1dfa563d62fcb2cf121904fac39224cf4dfeeb332e5461b9e5e3e6304391e729598d9fa0e5f082456b757b31ba9",
          "sha256": "964398ba85a0653d92ca29d6b1079c8fa87370bc579de4d822c0c85f32622aa5",
          "sha1": "8d96bc3164cb752d7c9c051b0bfd132d3ed3e524",
          "md5": "ff6602e39cdb47781707661eaba6c432"
        }
      ]
    }
  ]
}
