{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.4/nativeBridge-annotation-1.0.4.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation.klib",
          "url": "nativeBridge-annotation-macosx64-1.0.4.klib",
          "size": 23724,
          "sha512": "a5d08aa7ab5ef86d5c1e0d08baf7e67021ea13ff5f925ed538d20efdf3b122278e1725fd57436883325f4e4fe559c0b3c1c8b08125dd578e12eb0c2652eab5c4",
          "sha256": "b155361ec98aa55f548e74d9fbc4cb9676eff28a9016c2222c84aab6de6f3dd5",
          "sha1": "9f5dc966d8ed89b85f9c753f19fd7bf3cd151bb7",
          "md5": "cf63b9ce67602d74efd98843921ddb4e"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-macosx64-1.0.4-sources.jar",
          "url": "nativeBridge-annotation-macosx64-1.0.4-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-macosx64-1.0.4-metadata.jar",
          "url": "nativeBridge-annotation-macosx64-1.0.4-metadata.jar",
          "size": 261,
          "sha512": "cf3cfb0e516a20f0c8ad3b70846b789c04ddfd300dd26f27f7ac12f1577cdd446074443bb45b85acc11b02cc97a50af7ce1ca5a36e3303a4b95c9a712e313c71",
          "sha256": "8e54836cac3e8ade9fe678f9c6e4d501a7dbcb99d3475d0a4ed7919858c0ee7d",
          "sha1": "ac0de346e509471dc02931a42228dc51392bfaab",
          "md5": "ed3d0cba0d5030959e867e25e1a09788"
        }
      ]
    }
  ]
}
