{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-processor/1.0.3/nativeBridge-processor-1.0.3.module",
    "group": "com.subscribe.nativebridge.processor",
    "module": "nativeBridge-processor",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-processor-jvm-1.0.3.jar",
          "url": "nativeBridge-processor-jvm-1.0.3.jar",
          "size": 17371,
          "sha512": "eb80368e24a27550790438b2a3b2d3eec813427c4922c3cdb3d649c2a53aa21a74649f50877de649ff83effceff74a788a7a4ef1be0490bc0927924ff35db9b6",
          "sha256": "5ecea8b98e21f37e8b4d9d207948020d104c77a30c8bf1e904f937b9bf138700",
          "sha1": "0909bae596269547209f1f1f6fe10d544f9ba074",
          "md5": "8942c736d0c140530c7f7cdccac5a766"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.0-1.0.8"
          }
        },
        {
          "group": "com.subscribe.nativebridge.annotation",
          "module": "nativeBridge-annotation",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-processor-jvm-1.0.3.jar",
          "url": "nativeBridge-processor-jvm-1.0.3.jar",
          "size": 17371,
          "sha512": "eb80368e24a27550790438b2a3b2d3eec813427c4922c3cdb3d649c2a53aa21a74649f50877de649ff83effceff74a788a7a4ef1be0490bc0927924ff35db9b6",
          "sha256": "5ecea8b98e21f37e8b4d9d207948020d104c77a30c8bf1e904f937b9bf138700",
          "sha1": "0909bae596269547209f1f1f6fe10d544f9ba074",
          "md5": "8942c736d0c140530c7f7cdccac5a766"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-processor-jvm-1.0.3-sources.jar",
          "url": "nativeBridge-processor-jvm-1.0.3-sources.jar",
          "size": 3441,
          "sha512": "429f44c9f695aada170494356934c2602c24383ae17d2a0c82975dca106818d3fe5460529278a68f5a8529166a76df83a9588aa8499c6d0da083a48cf2a41ec8",
          "sha256": "bbd64d2f98148bf738ed3a9a2a13b2f028cdbd58f28b58d6631c4c02577cc3ca",
          "sha1": "62b08ed9ac6e05994fb196064dcfe82e54c21f32",
          "md5": "a3c8c7ba8b6009c82e636c33a777634e"
        }
      ]
    }
  ]
}
