{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.3/nativeBridge-annotation-1.0.3.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.3.jar",
          "url": "nativeBridge-annotation-jvm-1.0.3.jar",
          "size": 21977,
          "sha512": "0e52e3fd69a3d929c0bd862de73a5b8ef2b50f3fb9e23efd4333e9f3d9431aac5dbb80d81b592535e861eaa180ed58b803888f8623e64fb0e94aaed7e8b8fee9",
          "sha256": "32ea82b49d948ea7f07c75b585d01e33fc7a0df0e845175d6f93371a91604e33",
          "sha1": "7233c92cfaa7d23df0cb86a12ced4d3f70604576",
          "md5": "cc90cdd145f338d26c4606b8fd027451"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.3.jar",
          "url": "nativeBridge-annotation-jvm-1.0.3.jar",
          "size": 21977,
          "sha512": "0e52e3fd69a3d929c0bd862de73a5b8ef2b50f3fb9e23efd4333e9f3d9431aac5dbb80d81b592535e861eaa180ed58b803888f8623e64fb0e94aaed7e8b8fee9",
          "sha256": "32ea82b49d948ea7f07c75b585d01e33fc7a0df0e845175d6f93371a91604e33",
          "sha1": "7233c92cfaa7d23df0cb86a12ced4d3f70604576",
          "md5": "cc90cdd145f338d26c4606b8fd027451"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.3-sources.jar",
          "url": "nativeBridge-annotation-jvm-1.0.3-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    }
  ]
}
